version: '3.7'
services:
  backend:
    networks:
      - live
    build: ./src
    command: flask run --host=0.0.0.0
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 5000:5000
  db:
    networks:
      - live
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev
networks:
  live:
volumes:
  postgres_data:
